/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/buziraco/model.glb -t 
Author: vasian-65 (https://sketchfab.com/vasian-65)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gargoyle-f59478c6fdd6468f90826775c01fe1e0
Title: Gargoyle
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_11: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    eyes: THREE.MeshStandardMaterial
    head: THREE.MeshStandardMaterial
    wings: THREE.MeshStandardMaterial
    bodi: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Take 001'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Buziraco(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(getModelPath('buziraco')) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="03fef5bfbf58462aa8cc8c28621e1bbbfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" scale={10} />
                  <group name="Object_8" scale={10} />
                  <group name="Object_10" scale={10} />
                  <group name="Object_12" scale={10} />
                  <group name="eyes" scale={0.194} />
                  <group name="head" scale={0.194} />
                  <group name="wings" scale={0.194} />
                  <group name="bodi" scale={0.194} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.eyes} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.head} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.wings} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.bodi} skeleton={nodes.Object_13.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('buziraco'))
