/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\caiman\model.glb -t 
Author: ArachnoBoy (https://sketchfab.com/vang807)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/crocky-rocky-e5ab6cd7ec0147a0bdfbd62be2e499d0
Title: Crocky Rocky
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Object_51: THREE.SkinnedMesh
    Object_54: THREE.SkinnedMesh
    Object_57: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    M_Crocodile: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Unreal Take'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Caiman(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(getModelPath('caiman')) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" position={[0.042, -1.492, 0.729]} rotation={[Math.PI / 2, 0, 0]} scale={0.067}>
                <group name="ANIM_Crocodile_BiteForward_RM_PreviewMeshfbx_1" rotation={[-Math.PI, 0, 0]} scale={0.01}>
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="Object_4_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <group name="Object_6_6_correction">
                            <group name="Object_6_6" />
                          </group>
                          <group name="Object_7_7_correction">
                            <group name="Object_7_7" />
                          </group>
                          <group name="Object_8_8_correction">
                            <group name="Object_8_8" />
                          </group>
                          <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.M_Crocodile} skeleton={nodes.Object_51.skeleton} />
                          <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.M_Crocodile} skeleton={nodes.Object_54.skeleton} />
                          <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.M_Crocodile} skeleton={nodes.Object_57.skeleton} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('caiman'))
