/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cross/model.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    group606943721: THREE.Mesh
  }
  materials: {
    mat22: THREE.MeshStandardMaterial
  }
}

export function Cross(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('cross')) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group606943721.geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload(getModelPath('cross'))
