/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\demon2\model.glb -t 
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'
import { RapierRigidBody } from '@react-three/rapier'
import { distance2Points } from '@/helpers/distance'

type GLTFResult = GLTF & {
  nodes: {
    Demon_1: THREE.SkinnedMesh
    Demon_2: THREE.SkinnedMesh
    Demon_3: THREE.SkinnedMesh
    Demon_4: THREE.SkinnedMesh
    Trident: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Demon_Main: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Eye_White: THREE.MeshStandardMaterial
    Eye_Black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'CharacterArmature|Death' | 'CharacterArmature|Duck' | 'CharacterArmature|HitReact' | 'CharacterArmature|Idle' | 'CharacterArmature|Jump' | 'CharacterArmature|Jump_Idle' | 'CharacterArmature|Jump_Land' | 'CharacterArmature|No' | 'CharacterArmature|Punch' | 'CharacterArmature|Run' | 'CharacterArmature|Walk' | 'CharacterArmature|Wave' | 'CharacterArmature|Weapon' | 'CharacterArmature|Yes'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type DemonProps = JSX.IntrinsicElements['group'] & {
  rigidBodyRef?: MutableRefObject<RapierRigidBody | undefined>
  characterRef?: MutableRefObject<RapierRigidBody | undefined>
  attack?: () => void
}

export function Demon2(props: DemonProps) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(getModelPath('demon2')) as GLTFResult
  const { actions } = useAnimations(animations, group)

  const [attack, setAttack] = useState<boolean>(false)

  useEffect(() => {
    const animation = attack ? 'CharacterArmature|Punch' : 'CharacterArmature|Idle';
    actions[animation]?.reset().fadeIn(0.2).play();
    return () => {
      actions[animation]?.fadeOut(0.2);
    };
  }, [attack, actions]);

  useEffect(() => {
    if (props.rigidBodyRef?.current && props.characterRef?.current) {
      const distance = distance2Points(
        props.rigidBodyRef.current.translation(),
        props.characterRef.current.translation()
      )
      if (distance <= 30) {
        setAttack(true)
        if(props.attack) {
          props.attack()
        }
      }else {
        setAttack(false)
      }
    }
  }, [props])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Demon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Demon_1" geometry={nodes.Demon_1.geometry} material={materials.Demon_Main} skeleton={nodes.Demon_1.skeleton} />
            <skinnedMesh name="Demon_2" geometry={nodes.Demon_2.geometry} material={materials.Black} skeleton={nodes.Demon_2.skeleton} />
            <skinnedMesh name="Demon_3" geometry={nodes.Demon_3.geometry} material={materials.Eye_White} skeleton={nodes.Demon_3.skeleton} />
            <skinnedMesh name="Demon_4" geometry={nodes.Demon_4.geometry} material={materials.Eye_Black} skeleton={nodes.Demon_4.skeleton} />
          </group>
          <skinnedMesh name="Trident" geometry={nodes.Trident.geometry} material={materials.Black} skeleton={nodes.Trident.skeleton} position={[1.895, 1.734, -0.17]} scale={75.326} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('demon2'))
