/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\map1\model.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_2001: THREE.Mesh
    Object_3001: THREE.Mesh
    Object_4001: THREE.Mesh
    Object_5001: THREE.Mesh
    Object_6001: THREE.Mesh
    Object_7001: THREE.Mesh
    Object_2002: THREE.Mesh
    Object_3002: THREE.Mesh
    Object_4002: THREE.Mesh
    Object_5002: THREE.Mesh
    Object_6002: THREE.Mesh
    Object_7002: THREE.Mesh
    Object_2003: THREE.Mesh
    Object_3003: THREE.Mesh
    Object_4003: THREE.Mesh
    Object_5003: THREE.Mesh
    Object_6003: THREE.Mesh
    Object_7003: THREE.Mesh
    Object_2004: THREE.Mesh
    Object_3004: THREE.Mesh
    Object_4004: THREE.Mesh
    Object_5004: THREE.Mesh
    Object_6004: THREE.Mesh
    Object_7004: THREE.Mesh
    Object_2005: THREE.Mesh
    Object_3005: THREE.Mesh
    Object_4005: THREE.Mesh
    Object_5005: THREE.Mesh
    Object_6005: THREE.Mesh
    Object_7005: THREE.Mesh
    Object_3006: THREE.Mesh
    Object_4006: THREE.Mesh
    LOD0_lemon_grass_Mat_0: THREE.Mesh
    LOD1_lemon_grass_Mat_0: THREE.Mesh
    LOD2_lemon_grass_Mat_0: THREE.Mesh
    LOD0_lemon_grass_Mat_0001: THREE.Mesh
    LOD1_lemon_grass_Mat_0001: THREE.Mesh
    LOD2_lemon_grass_Mat_0001: THREE.Mesh
    LOD0_lemon_grass_Mat_0002: THREE.Mesh
    LOD1_lemon_grass_Mat_0002: THREE.Mesh
    LOD2_lemon_grass_Mat_0002: THREE.Mesh
    LOD0_lemon_grass_Mat_0003: THREE.Mesh
    LOD1_lemon_grass_Mat_0003: THREE.Mesh
    LOD2_lemon_grass_Mat_0003: THREE.Mesh
    LOD0_lemon_grass_Mat_0004: THREE.Mesh
    LOD1_lemon_grass_Mat_0004: THREE.Mesh
    LOD2_lemon_grass_Mat_0004: THREE.Mesh
    LOD0_lemon_grass_Mat_0005: THREE.Mesh
    LOD1_lemon_grass_Mat_0005: THREE.Mesh
    LOD2_lemon_grass_Mat_0005: THREE.Mesh
    LOD0_lemon_grass_Mat_0006: THREE.Mesh
    LOD1_lemon_grass_Mat_0006: THREE.Mesh
    LOD2_lemon_grass_Mat_0006: THREE.Mesh
    Object_14: THREE.Mesh
    Object_12: THREE.Mesh
    Object_10: THREE.Mesh
    Object_6006: THREE.Mesh
    Object_4007: THREE.Mesh
    Object_8: THREE.Mesh
    LOD1_lemon_grass_Mat_0007: THREE.Mesh
    LOD0_lemon_grass_Mat_0007: THREE.Mesh
    LOD0_lemon_grass_Mat_0008: THREE.Mesh
    LOD0_lemon_grass_Mat_0009: THREE.Mesh
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cone007: THREE.Mesh
    Cone007_1: THREE.Mesh
    Cone007_2: THREE.Mesh
    Cone002: THREE.Mesh
    Cone002_1: THREE.Mesh
    Icosphere030: THREE.Mesh
    Icosphere030_1: THREE.Mesh
    Icosphere030_2: THREE.Mesh
    Icosphere030_3: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere003_1: THREE.Mesh
    Icosphere003_2: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001_2: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere001_1: THREE.Mesh
    Icosphere001_2: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere002_1: THREE.Mesh
    Icosphere002_2: THREE.Mesh
    Icosphere002_3: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cylinder001_3: THREE.Mesh
    Cone003: THREE.Mesh
    Cone003_1: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere004_1: THREE.Mesh
    Icosphere004_2: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere005_1: THREE.Mesh
    Icosphere005_2: THREE.Mesh
    Icosphere005_3: THREE.Mesh
    Cone004: THREE.Mesh
    Cone004_1: THREE.Mesh
    Cube031: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube031_3: THREE.Mesh
    Cube031_4: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere006_1: THREE.Mesh
    Icosphere006_2: THREE.Mesh
    Cone005: THREE.Mesh
    Cone005_1: THREE.Mesh
    Cone006: THREE.Mesh
    Cone006_1: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere007_1: THREE.Mesh
    Icosphere007_2: THREE.Mesh
    Icosphere007_3: THREE.Mesh
    Icosphere008: THREE.Mesh
    Icosphere008_1: THREE.Mesh
    Icosphere008_2: THREE.Mesh
    Icosphere008_3: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder006_2: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder007_1: THREE.Mesh
  }
  materials: {
    ['textured_0.002']: THREE.MeshBasicMaterial
    signs: THREE.MeshBasicMaterial
    walls: THREE.MeshBasicMaterial
    lemon_grass_Mat: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.001']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.002']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.003']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.004']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Tree5_Leaves2: THREE.MeshStandardMaterial
    Tree5_Leaves1: THREE.MeshStandardMaterial
    Tree5_Trunk: THREE.MeshStandardMaterial
    Tree4_Leaves1: THREE.MeshStandardMaterial
    Tree4_Leaves2: THREE.MeshStandardMaterial
    Tree4_Trunk: THREE.MeshStandardMaterial
    Tree3_Leaves1: THREE.MeshStandardMaterial
    Tree3_Trunk: THREE.MeshStandardMaterial
    Tree2_Leaves1: THREE.MeshStandardMaterial
    Tree2_Leaves2: THREE.MeshStandardMaterial
    Tree2_Leaves3: THREE.MeshStandardMaterial
    Tree2_Trunk: THREE.MeshStandardMaterial
    Tree1_Leaves1: THREE.MeshStandardMaterial
    Tree1_Leaves2: THREE.MeshStandardMaterial
    Tree1_Trunk: THREE.MeshStandardMaterial
    ['Tree4_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree4_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree4_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.001']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree5_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.002']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.002']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    ['wood light']: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    wood3: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.003']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.003']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.003']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshPhysicalMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshPhysicalMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshPhysicalMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshPhysicalMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshPhysicalMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshPhysicalMaterial
  }
}

export function Map1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('map1')) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[63.234, 5.468, -78.553]} rotation={[-Math.PI, 0, 0]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[62.52, 5.462, -43.626]} rotation={[0, -0.016, Math.PI]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5001.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6001.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7001.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[62.57, 5.418, -2.276]} rotation={[-Math.PI, 0, 0]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2002.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3002.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4002.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5002.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6002.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7002.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[61.816, 5.485, 35.781]} rotation={[0, -0.016, Math.PI]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2003.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3003.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4003.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5003.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6003.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7003.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[44.497, 5.487, 60.151]} rotation={[0, 1.551, -Math.PI]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2004.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3004.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4004.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5004.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6004.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7004.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[8.34, 5.453, 59.837]} rotation={[0, -1.557, Math.PI]} scale={[2.761, 0.996, 6.834]}>
        <mesh geometry={nodes.Object_2005.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_3005.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_4005.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh geometry={nodes.Object_5005.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_6005.geometry} material={materials['textured_0.002']} />
        <mesh geometry={nodes.Object_7005.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[18.431, 5.618, 12.583]} rotation={[-Math.PI / 2, 0, -3.13]} scale={[3.489, 3.489, 1]}>
        <mesh geometry={nodes.Object_3006.geometry} material={materials.signs} />
        <mesh geometry={nodes.Object_4006.geometry} material={materials.walls} position={[13.598, -2.304, -0.422]} scale={[1.962, 1.994, 1.936]} />
      </group>
      <group position={[55.947, 5.958, -27.545]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.352, 5.198, -18.362]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.362, 4.702, -7.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.645, 5.245, 3.758]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.54, 5.151, 15.731]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.765, 4.913, 30.085]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[56.794, 5.137, 46.177]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} />
          <mesh geometry={nodes.LOD2_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[54.013, 7.609, -30.717]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.232, 14.506, 2.149]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.247, -0.558, -4.007]} rotation={[-0.071, 0.06, -0.233]} scale={[0.025, 0.043, 0.046]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.004']} position={[-553.573, -96.142, -12.101]} />
          </group>
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} position={[-12.281, -0.258, -0.317]} scale={1.019} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} position={[-12.281, -0.258, -0.317]} />
          <mesh geometry={nodes.Object_6006.geometry} material={materials['Material.003']} position={[-12.281, -0.258, -0.317]} />
          <mesh geometry={nodes.Object_4007.geometry} material={materials['Material.002']} position={[-12.281, -0.258, -0.317]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[-12.116, -0.111, -0.365]} />
        </group>
      </group>
      <group position={[55.947, 5.958, -27.545]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD1_lemon_grass_Mat_0007.geometry} material={materials['lemon_grass_Mat.001']} position={[-3.207, -0.219, -3194.964]} />
        </group>
      </group>
      <group position={[54.482, 5.847, -97.867]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0007.geometry} material={materials['lemon_grass_Mat.002']} position={[0.962, -0.977, -8.112]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <group position={[94.18, 6.976, -97.448]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0008.geometry} material={materials['lemon_grass_Mat.003']} position={[0.962, -2.741, 7.841]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <group position={[95.955, 8.116, -96.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[47.842, 1, 47.842]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.LOD0_lemon_grass_Mat_0009.geometry} material={materials['lemon_grass_Mat.004']} position={[5.155, -5.262, 155.492]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} />
      <group position={[-7.907, 0, 0]} scale={[0.796, 0.796, 1]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Tree5_Leaves2} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Tree5_Leaves1} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Tree5_Trunk} />
      </group>
      <group position={[-14.224, 1.536, 15.261]} scale={[0.697, 0.535, 0.768]}>
        <mesh geometry={nodes.Cone007.geometry} material={materials.Tree4_Leaves1} />
        <mesh geometry={nodes.Cone007_1.geometry} material={materials.Tree4_Leaves2} />
        <mesh geometry={nodes.Cone007_2.geometry} material={materials.Tree4_Trunk} />
      </group>
      <group position={[-8.157, 0.328, 0]} scale={[0.897, 0.745, 0.831]}>
        <mesh geometry={nodes.Cone002.geometry} material={materials.Tree3_Leaves1} />
        <mesh geometry={nodes.Cone002_1.geometry} material={materials.Tree3_Trunk} />
      </group>
      <group scale={[0.855, 0.855, 1]}>
        <mesh geometry={nodes.Icosphere030.geometry} material={materials.Tree2_Leaves1} />
        <mesh geometry={nodes.Icosphere030_1.geometry} material={materials.Tree2_Leaves2} />
        <mesh geometry={nodes.Icosphere030_2.geometry} material={materials.Tree2_Leaves3} />
        <mesh geometry={nodes.Icosphere030_3.geometry} material={materials.Tree2_Trunk} />
      </group>
      <group scale={[1, 0.883, 0.883]}>
        <mesh geometry={nodes.Icosphere003.geometry} material={materials.Tree1_Leaves1} />
        <mesh geometry={nodes.Icosphere003_1.geometry} material={materials.Tree1_Leaves2} />
        <mesh geometry={nodes.Icosphere003_2.geometry} material={materials.Tree1_Trunk} />
      </group>
      <group position={[-8.526, 0.594, 16.378]} scale={[0.668, 0.513, 0.768]}>
        <mesh geometry={nodes.Cone001.geometry} material={materials['Tree4_Leaves1.001']} />
        <mesh geometry={nodes.Cone001_1.geometry} material={materials['Tree4_Leaves2.001']} />
        <mesh geometry={nodes.Cone001_2.geometry} material={materials['Tree4_Trunk.001']} />
      </group>
      <group position={[-6.001, 0, -0.293]} scale={[0.854, 0.854, 1]}>
        <mesh geometry={nodes.Icosphere001.geometry} material={materials['Tree1_Leaves1.001']} />
        <mesh geometry={nodes.Icosphere001_1.geometry} material={materials['Tree1_Leaves2.001']} />
        <mesh geometry={nodes.Icosphere001_2.geometry} material={materials['Tree1_Trunk.001']} />
      </group>
      <group position={[-9.923, 0.858, 3.032]} scale={[0.859, 0.859, 1]}>
        <mesh geometry={nodes.Icosphere002.geometry} material={materials['Tree2_Leaves1.001']} />
        <mesh geometry={nodes.Icosphere002_1.geometry} material={materials['Tree2_Leaves2.001']} />
        <mesh geometry={nodes.Icosphere002_2.geometry} material={materials['Tree2_Leaves3.001']} />
        <mesh geometry={nodes.Icosphere002_3.geometry} material={materials['Tree2_Trunk.001']} />
      </group>
      <group position={[-2.757, 0.279, 0.327]} scale={[0.941, 0.832, 0.884]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Tree5_Leaves2.001']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Tree5_Leaves1.001']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Tree5_Trunk.001']} />
      </group>
      <group position={[-5.715, -0.312, 0]} scale={[0.872, 0.786, 0.902]}>
        <mesh geometry={nodes.Cone003.geometry} material={materials['Tree3_Leaves1.001']} />
        <mesh geometry={nodes.Cone003_1.geometry} material={materials['Tree3_Trunk.001']} />
      </group>
      <group position={[-8.332, 0, 0]} scale={[0.902, 0.902, 1]}>
        <mesh geometry={nodes.Icosphere004.geometry} material={materials['Tree1_Leaves1.002']} />
        <mesh geometry={nodes.Icosphere004_1.geometry} material={materials['Tree1_Leaves2.002']} />
        <mesh geometry={nodes.Icosphere004_2.geometry} material={materials['Tree1_Trunk.002']} />
      </group>
      <group position={[0.929, -1.276, -10.001]}>
        <mesh geometry={nodes.Icosphere005.geometry} material={materials['Tree2_Leaves1.002']} />
        <mesh geometry={nodes.Icosphere005_1.geometry} material={materials['Tree2_Leaves2.002']} />
        <mesh geometry={nodes.Icosphere005_2.geometry} material={materials['Tree2_Leaves3.002']} />
        <mesh geometry={nodes.Icosphere005_3.geometry} material={materials['Tree2_Trunk.002']} />
      </group>
      <group position={[11.228, 2.265, -4.584]} scale={[0.791, 0.791, 1]}>
        <mesh geometry={nodes.Cone004.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh geometry={nodes.Cone004_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[88.098, 5.13, -6.64]} rotation={[3.139, 0.064, -3.124]} scale={[6.741, 7.25, 7.881]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.dark} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['wood light']} />
        <mesh geometry={nodes.Cube031_3.geometry} material={materials.blue} />
        <mesh geometry={nodes.Cube031_4.geometry} material={materials.wood3} />
      </group>
      <group position={[110.101, 0.383, 94.584]} rotation={[-0.042, 0.136, -0.054]} scale={[0.986, 0.898, 0.911]}>
        <mesh geometry={nodes.Icosphere006.geometry} material={materials['Tree1_Leaves1.001']} />
        <mesh geometry={nodes.Icosphere006_1.geometry} material={materials['Tree1_Leaves2.001']} />
        <mesh geometry={nodes.Icosphere006_2.geometry} material={materials['Tree1_Trunk.001']} />
      </group>
      <group position={[-53.009, 0.552, 172.442]} scale={[1, 0.956, 0.956]}>
        <mesh geometry={nodes.Cone005.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh geometry={nodes.Cone005_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[5.54, 0.07, 114.438]} scale={[1, 0.956, 0.956]}>
        <mesh geometry={nodes.Cone006.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh geometry={nodes.Cone006_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[-79.895, -1.576, 143.606]}>
        <mesh geometry={nodes.Icosphere007.geometry} material={materials['Tree2_Leaves1.002']} />
        <mesh geometry={nodes.Icosphere007_1.geometry} material={materials['Tree2_Leaves2.002']} />
        <mesh geometry={nodes.Icosphere007_2.geometry} material={materials['Tree2_Leaves3.002']} />
        <mesh geometry={nodes.Icosphere007_3.geometry} material={materials['Tree2_Trunk.002']} />
      </group>
      <group position={[15.373, -2.045, 150.76]}>
        <mesh geometry={nodes.Icosphere008.geometry} material={materials['Tree2_Leaves1.003']} />
        <mesh geometry={nodes.Icosphere008_1.geometry} material={materials['Tree2_Leaves2.003']} />
        <mesh geometry={nodes.Icosphere008_2.geometry} material={materials['Tree2_Leaves3.003']} />
        <mesh geometry={nodes.Icosphere008_3.geometry} material={materials['Tree2_Trunk.003']} />
      </group>
      <group position={[-26.823, 7.86, 97.028]} scale={[0.166, 0.161, 0.166]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-46.135, 8.461, 96.244]} scale={[0.177, 0.172, 0.177]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.008']} />
      </group>
      <group position={[13.858, 8.199, 97.234]} scale={[0.166, 0.161, 0.166]}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[31.431, 8.066, 98.711]} scale={[0.166, 0.161, 0.166]}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-93.162, 7.464, 89.03]} scale={[0.177, 0.172, 0.177]}>
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-72.016, 7.33, 97.163]} scale={[0.177, 0.172, 0.177]}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.016']} />
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('map1'))
