/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\map1\model.glb -t -s 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_2001: THREE.Mesh
    Object_3001: THREE.Mesh
    Object_4001: THREE.Mesh
    Object_5001: THREE.Mesh
    Object_6001: THREE.Mesh
    Object_7001: THREE.Mesh
    Object_2002: THREE.Mesh
    Object_3002: THREE.Mesh
    Object_4002: THREE.Mesh
    Object_5002: THREE.Mesh
    Object_6002: THREE.Mesh
    Object_7002: THREE.Mesh
    Object_2003: THREE.Mesh
    Object_3003: THREE.Mesh
    Object_4003: THREE.Mesh
    Object_5003: THREE.Mesh
    Object_6003: THREE.Mesh
    Object_7003: THREE.Mesh
    Object_2004: THREE.Mesh
    Object_3004: THREE.Mesh
    Object_4004: THREE.Mesh
    Object_5004: THREE.Mesh
    Object_6004: THREE.Mesh
    Object_7004: THREE.Mesh
    Object_2005: THREE.Mesh
    Object_3005: THREE.Mesh
    Object_4005: THREE.Mesh
    Object_5005: THREE.Mesh
    Object_6005: THREE.Mesh
    Object_7005: THREE.Mesh
    Object_4006: THREE.Mesh
    LOD0_lemon_grass_Mat_0: THREE.Mesh
    LOD1_lemon_grass_Mat_0: THREE.Mesh
    LOD2_lemon_grass_Mat_0: THREE.Mesh
    LOD0_lemon_grass_Mat_0001: THREE.Mesh
    LOD1_lemon_grass_Mat_0001: THREE.Mesh
    LOD2_lemon_grass_Mat_0001: THREE.Mesh
    LOD0_lemon_grass_Mat_0002: THREE.Mesh
    LOD1_lemon_grass_Mat_0002: THREE.Mesh
    LOD2_lemon_grass_Mat_0002: THREE.Mesh
    LOD0_lemon_grass_Mat_0003: THREE.Mesh
    LOD1_lemon_grass_Mat_0003: THREE.Mesh
    LOD2_lemon_grass_Mat_0003: THREE.Mesh
    LOD0_lemon_grass_Mat_0004: THREE.Mesh
    LOD1_lemon_grass_Mat_0004: THREE.Mesh
    LOD2_lemon_grass_Mat_0004: THREE.Mesh
    LOD0_lemon_grass_Mat_0005: THREE.Mesh
    LOD1_lemon_grass_Mat_0005: THREE.Mesh
    LOD2_lemon_grass_Mat_0005: THREE.Mesh
    LOD0_lemon_grass_Mat_0006: THREE.Mesh
    LOD1_lemon_grass_Mat_0006: THREE.Mesh
    LOD2_lemon_grass_Mat_0006: THREE.Mesh
    Object_12: THREE.Mesh
    Object_6006: THREE.Mesh
    Object_4007: THREE.Mesh
    Object_8: THREE.Mesh
    LOD1_lemon_grass_Mat_0007: THREE.Mesh
    LOD0_lemon_grass_Mat_0007: THREE.Mesh
    LOD0_lemon_grass_Mat_0008: THREE.Mesh
    LOD0_lemon_grass_Mat_0009: THREE.Mesh
    Object_10: THREE.Mesh
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cone007: THREE.Mesh
    Cone007_1: THREE.Mesh
    Cone007_2: THREE.Mesh
    Cone002: THREE.Mesh
    Cone002_1: THREE.Mesh
    Icosphere030: THREE.Mesh
    Icosphere030_1: THREE.Mesh
    Icosphere030_2: THREE.Mesh
    Icosphere030_3: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere003_1: THREE.Mesh
    Icosphere003_2: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001_2: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere001_1: THREE.Mesh
    Icosphere001_2: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere002_1: THREE.Mesh
    Icosphere002_2: THREE.Mesh
    Icosphere002_3: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cylinder001_3: THREE.Mesh
    Cone003: THREE.Mesh
    Cone003_1: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere004_1: THREE.Mesh
    Icosphere004_2: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere005_1: THREE.Mesh
    Icosphere005_2: THREE.Mesh
    Icosphere005_3: THREE.Mesh
    Cone004: THREE.Mesh
    Cone004_1: THREE.Mesh
    Cube031: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube031_3: THREE.Mesh
    Cube031_4: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere006_1: THREE.Mesh
    Icosphere006_2: THREE.Mesh
    Cone005: THREE.Mesh
    Cone005_1: THREE.Mesh
    Cone006: THREE.Mesh
    Cone006_1: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere007_1: THREE.Mesh
    Icosphere007_2: THREE.Mesh
    Icosphere007_3: THREE.Mesh
    Icosphere008: THREE.Mesh
    Icosphere008_1: THREE.Mesh
    Icosphere008_2: THREE.Mesh
    Icosphere008_3: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder006_2: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder007_1: THREE.Mesh
  }
  materials: {
    ['textured_0.002']: THREE.MeshBasicMaterial
    walls: THREE.MeshBasicMaterial
    lemon_grass_Mat: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.001']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.002']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.003']: THREE.MeshStandardMaterial
    ['lemon_grass_Mat.004']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Tree5_Leaves2: THREE.MeshStandardMaterial
    Tree5_Leaves1: THREE.MeshStandardMaterial
    Tree5_Trunk: THREE.MeshStandardMaterial
    Tree4_Leaves1: THREE.MeshStandardMaterial
    Tree4_Leaves2: THREE.MeshStandardMaterial
    Tree4_Trunk: THREE.MeshStandardMaterial
    Tree3_Leaves1: THREE.MeshStandardMaterial
    Tree3_Trunk: THREE.MeshStandardMaterial
    Tree2_Leaves1: THREE.MeshStandardMaterial
    Tree2_Leaves2: THREE.MeshStandardMaterial
    Tree2_Leaves3: THREE.MeshStandardMaterial
    Tree2_Trunk: THREE.MeshStandardMaterial
    Tree1_Leaves1: THREE.MeshStandardMaterial
    Tree1_Leaves2: THREE.MeshStandardMaterial
    Tree1_Trunk: THREE.MeshStandardMaterial
    ['Tree4_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree4_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree4_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.001']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree5_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.002']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.002']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    ['wood light']: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    wood3: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.003']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.003']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.003']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshPhysicalMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshPhysicalMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshPhysicalMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshPhysicalMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshPhysicalMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshPhysicalMaterial
  }
}

export function Map1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('map1')) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[41.161, 4.505, -27.807]} rotation={[-Math.PI, 0, 0]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[40.809, 4.502, -10.531]} rotation={[0, -0.016, Math.PI]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2001.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3001.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4001.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5001.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6001.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7001.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[40.833, 4.481, 9.922]} rotation={[-Math.PI, 0, 0]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2002.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3002.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4002.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5002.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6002.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7002.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[40.46, 4.514, 28.746]} rotation={[0, -0.016, Math.PI]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2003.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3003.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4003.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5003.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6003.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7003.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[31.894, 4.515, 40.8]} rotation={[0, 1.551, -Math.PI]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2004.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3004.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4004.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5004.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6004.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7004.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[14.009, 4.498, 40.645]} rotation={[0, -1.557, Math.PI]} scale={[1.365, 0.492, 3.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2005.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3005.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4005.geometry} material={materials['textured_0.002']} scale={[1.012, 1.012, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5005.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6005.geometry} material={materials['textured_0.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7005.geometry} material={materials['textured_0.002']} />
      </group>
      <group position={[19.001, 4.58, 17.272]} rotation={[-Math.PI / 2, 0, -3.13]} scale={[1.726, 1.726, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_4006.geometry} material={materials.walls} position={[13.598, -2.304, -0.422]} scale={[1.962, 1.994, 1.936]} />
      </group>
      <group position={[37.557, 4.748, -2.577]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.757, 4.372, 1.965]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0001.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.762, 4.126, 7.333]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0002.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.903, 4.395, 12.906]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0003.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.85, 4.349, 18.828]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0004.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.962, 4.231, 25.928]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0005.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[37.976, 4.341, 33.888]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} scale={[1, 1, 40.64]} />
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} />
          <mesh castShadow receiveShadow geometry={nodes.LOD2_lemon_grass_Mat_0006.geometry} material={materials.lemon_grass_Mat} />
        </group>
      </group>
      <group position={[36.601, 5.564, -4.146]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.609, 7.175, 1.063]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.003']} position={[-12.281, -0.258, -0.317]} scale={1.019} />
          <mesh castShadow receiveShadow geometry={nodes.Object_6006.geometry} material={materials['Material.003']} position={[-12.281, -0.258, -0.317]} />
          <mesh castShadow receiveShadow geometry={nodes.Object_4007.geometry} material={materials['Material.002']} position={[-12.281, -0.258, -0.317]} />
          <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[-12.116, -0.111, -0.365]} />
        </group>
      </group>
      <group position={[37.557, 4.748, -2.577]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD1_lemon_grass_Mat_0007.geometry} material={materials['lemon_grass_Mat.001']} position={[-3.207, -0.219, -3194.963]} />
        </group>
      </group>
      <group position={[36.832, 4.693, -37.361]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0007.geometry} material={materials['lemon_grass_Mat.002']} position={[0.962, -0.977, -8.113]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <group position={[56.469, 5.251, -37.153]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0008.geometry} material={materials['lemon_grass_Mat.003']} position={[0.962, -2.741, 7.84]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <group position={[57.346, 5.815, -36.486]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.664, 0.495, 23.664]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.LOD0_lemon_grass_Mat_0009.geometry} material={materials['lemon_grass_Mat.004']} position={[5.155, -5.262, 155.492]} scale={[1, 1, 40.64]} />
        </group>
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.003']} position={[0.473, 1.273, 8.567]} scale={0.598} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[9.884, 1.801, 11.047]} scale={0.495} />
      <group position={[5.973, 1.801, 11.047]} scale={[0.393, 0.393, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Tree5_Leaves2} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials.Tree5_Leaves1} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials.Tree5_Trunk} />
      </group>
      <group position={[2.848, 2.56, 18.596]} scale={[0.345, 0.264, 0.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone007.geometry} material={materials.Tree4_Leaves1} />
        <mesh castShadow receiveShadow geometry={nodes.Cone007_1.geometry} material={materials.Tree4_Leaves2} />
        <mesh castShadow receiveShadow geometry={nodes.Cone007_2.geometry} material={materials.Tree4_Trunk} />
      </group>
      <group position={[5.85, 1.963, 11.047]} scale={[0.443, 0.369, 0.411]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone002.geometry} material={materials.Tree3_Leaves1} />
        <mesh castShadow receiveShadow geometry={nodes.Cone002_1.geometry} material={materials.Tree3_Trunk} />
      </group>
      <group position={[9.884, 1.801, 11.047]} scale={[0.423, 0.423, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere030.geometry} material={materials.Tree2_Leaves1} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere030_1.geometry} material={materials.Tree2_Leaves2} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere030_2.geometry} material={materials.Tree2_Leaves3} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere030_3.geometry} material={materials.Tree2_Trunk} />
      </group>
      <group position={[9.884, 1.801, 11.047]} scale={[0.495, 0.437, 0.437]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere003.geometry} material={materials.Tree1_Leaves1} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere003_1.geometry} material={materials.Tree1_Leaves2} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere003_2.geometry} material={materials.Tree1_Trunk} />
      </group>
      <group position={[5.667, 2.094, 19.149]} scale={[0.33, 0.254, 0.38]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone001.geometry} material={materials['Tree4_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone001_1.geometry} material={materials['Tree4_Leaves2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone001_2.geometry} material={materials['Tree4_Trunk.001']} />
      </group>
      <group position={[6.916, 1.801, 10.902]} scale={[0.423, 0.423, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={materials['Tree1_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere001_1.geometry} material={materials['Tree1_Leaves2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere001_2.geometry} material={materials['Tree1_Trunk.001']} />
      </group>
      <group position={[4.976, 2.225, 12.547]} scale={[0.425, 0.425, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={materials['Tree2_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere002_1.geometry} material={materials['Tree2_Leaves2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere002_2.geometry} material={materials['Tree2_Leaves3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere002_3.geometry} material={materials['Tree2_Trunk.001']} />
      </group>
      <group position={[8.52, 1.939, 11.209]} scale={[0.466, 0.412, 0.437]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_1.geometry} material={materials['Tree5_Leaves2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_2.geometry} material={materials['Tree5_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001_3.geometry} material={materials['Tree5_Trunk.001']} />
      </group>
      <group position={[7.057, 1.647, 11.047]} scale={[0.431, 0.389, 0.446]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone003.geometry} material={materials['Tree3_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone003_1.geometry} material={materials['Tree3_Trunk.001']} />
      </group>
      <group position={[5.763, 1.801, 11.047]} scale={[0.446, 0.446, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere004.geometry} material={materials['Tree1_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere004_1.geometry} material={materials['Tree1_Leaves2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere004_2.geometry} material={materials['Tree1_Trunk.002']} />
      </group>
      <group position={[10.344, 1.17, 6.101]} scale={0.495}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere005.geometry} material={materials['Tree2_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere005_1.geometry} material={materials['Tree2_Leaves2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere005_2.geometry} material={materials['Tree2_Leaves3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere005_3.geometry} material={materials['Tree2_Trunk.002']} />
      </group>
      <group position={[15.438, 2.921, 8.78]} scale={[0.391, 0.391, 0.495]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone004.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone004_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[53.46, 4.338, 7.763]} rotation={[3.139, 0.064, -3.124]} scale={[3.334, 3.586, 3.898]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube031.geometry} material={materials.wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cube031_1.geometry} material={materials.dark} />
        <mesh castShadow receiveShadow geometry={nodes.Cube031_2.geometry} material={materials['wood light']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube031_3.geometry} material={materials.blue} />
        <mesh castShadow receiveShadow geometry={nodes.Cube031_4.geometry} material={materials.wood3} />
      </group>
      <group position={[64.344, 1.99, 57.832]} rotation={[-0.042, 0.136, -0.054]} scale={[0.488, 0.444, 0.451]}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere006.geometry} material={materials['Tree1_Leaves1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere006_1.geometry} material={materials['Tree1_Leaves2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere006_2.geometry} material={materials['Tree1_Trunk.001']} />
      </group>
      <group position={[-16.336, 2.074, 96.343]} scale={[0.495, 0.473, 0.473]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone005.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone005_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[12.625, 1.835, 67.652]} scale={[0.495, 0.473, 0.473]}>
        <mesh castShadow receiveShadow geometry={nodes.Cone006.geometry} material={materials['Tree3_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cone006_1.geometry} material={materials['Tree3_Trunk.002']} />
      </group>
      <group position={[-29.634, 1.021, 82.079]} scale={0.495}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere007.geometry} material={materials['Tree2_Leaves1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere007_1.geometry} material={materials['Tree2_Leaves2.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere007_2.geometry} material={materials['Tree2_Leaves3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere007_3.geometry} material={materials['Tree2_Trunk.002']} />
      </group>
      <group position={[17.488, 0.789, 85.618]} scale={0.495}>
        <mesh castShadow receiveShadow geometry={nodes.Icosphere008.geometry} material={materials['Tree2_Leaves1.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere008_1.geometry} material={materials['Tree2_Leaves2.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere008_2.geometry} material={materials['Tree2_Leaves3.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Icosphere008_3.geometry} material={materials['Tree2_Trunk.003']} />
      </group>
      <group position={[-3.383, 5.689, 59.04]} scale={[0.082, 0.08, 0.082]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder004_1.geometry} material={materials['Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder004_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-12.935, 5.985, 58.652]} scale={[0.088, 0.085, 0.088]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials['Material.007']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials['Material.008']} />
      </group>
      <group position={[16.739, 5.856, 59.142]} scale={[0.082, 0.08, 0.082]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_1.geometry} material={materials['Material.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[25.431, 5.79, 59.873]} scale={[0.082, 0.08, 0.082]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder005_1.geometry} material={materials['Material.011']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder005_2.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-36.196, 5.492, 55.084]} scale={[0.088, 0.085, 0.088]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006_1.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006_2.geometry} material={materials['Material.014']} />
      </group>
      <group position={[-25.737, 5.426, 59.107]} scale={[0.088, 0.085, 0.088]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={materials['Material.015']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder007_1.geometry} material={materials['Material.016']} />
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('map1'))
