/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\map1\model.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001_2: THREE.Mesh
    Cone001_3: THREE.Mesh
    Cone001_4: THREE.Mesh
    Cone001_5: THREE.Mesh
    Cone001_6: THREE.Mesh
    Cone001_7: THREE.Mesh
    Cone001_8: THREE.Mesh
    Cone001_9: THREE.Mesh
    Cone001_10: THREE.Mesh
    Cone001_11: THREE.Mesh
    Cone001_12: THREE.Mesh
    Cone001_13: THREE.Mesh
    Cone001_14: THREE.Mesh
    Cone001_15: THREE.Mesh
    Cone001_16: THREE.Mesh
    Cone001_17: THREE.Mesh
    Cone001_18: THREE.Mesh
    Cone001_19: THREE.Mesh
    Cone001_20: THREE.Mesh
    Cone001_21: THREE.Mesh
    Cone001_22: THREE.Mesh
    Cone001_23: THREE.Mesh
    Cone001_24: THREE.Mesh
    Cone001_25: THREE.Mesh
    Cone001_26: THREE.Mesh
    Cone001_27: THREE.Mesh
    Cone001_28: THREE.Mesh
    Cone001_29: THREE.Mesh
    Cone001_30: THREE.Mesh
    Cone001_31: THREE.Mesh
    Cone001_32: THREE.Mesh
    Cone001_33: THREE.Mesh
    Cone001_34: THREE.Mesh
    Cone001_35: THREE.Mesh
    Cone001_36: THREE.Mesh
    Cone001_37: THREE.Mesh
    Cone001_38: THREE.Mesh
    Cone001_39: THREE.Mesh
    Cone001_40: THREE.Mesh
    Cone001_41: THREE.Mesh
    Cone001_42: THREE.Mesh
    Cone001_43: THREE.Mesh
    Cone001_44: THREE.Mesh
    Cone001_45: THREE.Mesh
    Cone001_46: THREE.Mesh
    Cone001_47: THREE.Mesh
    Cone001_48: THREE.Mesh
    Cone001_49: THREE.Mesh
    Cone001_50: THREE.Mesh
  }
  materials: {
    ['Tree4_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree4_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree4_Trunk.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Tree5_Leaves2: THREE.MeshStandardMaterial
    Tree5_Leaves1: THREE.MeshStandardMaterial
    Tree5_Trunk: THREE.MeshStandardMaterial
    Tree4_Leaves1: THREE.MeshStandardMaterial
    Tree4_Leaves2: THREE.MeshStandardMaterial
    Tree4_Trunk: THREE.MeshStandardMaterial
    Tree3_Leaves1: THREE.MeshStandardMaterial
    Tree3_Trunk: THREE.MeshStandardMaterial
    Tree2_Leaves1: THREE.MeshStandardMaterial
    Tree2_Leaves2: THREE.MeshStandardMaterial
    Tree2_Leaves3: THREE.MeshStandardMaterial
    Tree2_Trunk: THREE.MeshStandardMaterial
    Tree1_Leaves1: THREE.MeshStandardMaterial
    Tree1_Leaves2: THREE.MeshStandardMaterial
    Tree1_Trunk: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.001']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree5_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.002']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.002']: THREE.MeshStandardMaterial
    ['Scene_-_Root']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshPhysicalMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshPhysicalMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshPhysicalMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshPhysicalMaterial
  }
}

export function Map1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('map1')) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Cone001.geometry} material={materials['Tree4_Leaves1.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_1.geometry} material={materials['Tree4_Leaves2.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_2.geometry} material={materials['Tree4_Trunk.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_3.geometry} material={materials['Material.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_4.geometry} material={materials.Tree5_Leaves2} />
      <mesh receiveShadow geometry={nodes.Cone001_5.geometry} material={materials.Tree5_Leaves1} />
      <mesh receiveShadow geometry={nodes.Cone001_6.geometry} material={materials.Tree5_Trunk} />
      <mesh receiveShadow geometry={nodes.Cone001_7.geometry} material={materials.Tree4_Leaves1} />
      <mesh receiveShadow geometry={nodes.Cone001_8.geometry} material={materials.Tree4_Leaves2} />
      <mesh receiveShadow geometry={nodes.Cone001_9.geometry} material={materials.Tree4_Trunk} />
      <mesh receiveShadow geometry={nodes.Cone001_10.geometry} material={materials.Tree3_Leaves1} />
      <mesh receiveShadow geometry={nodes.Cone001_11.geometry} material={materials.Tree3_Trunk} />
      <mesh receiveShadow geometry={nodes.Cone001_12.geometry} material={materials.Tree2_Leaves1} />
      <mesh receiveShadow geometry={nodes.Cone001_13.geometry} material={materials.Tree2_Leaves2} />
      <mesh receiveShadow geometry={nodes.Cone001_14.geometry} material={materials.Tree2_Leaves3} />
      <mesh receiveShadow geometry={nodes.Cone001_15.geometry} material={materials.Tree2_Trunk} />
      <mesh receiveShadow geometry={nodes.Cone001_16.geometry} material={materials.Tree1_Leaves1} />
      <mesh receiveShadow geometry={nodes.Cone001_17.geometry} material={materials.Tree1_Leaves2} />
      <mesh receiveShadow geometry={nodes.Cone001_18.geometry} material={materials.Tree1_Trunk} />
      <mesh receiveShadow geometry={nodes.Cone001_19.geometry} material={materials['Tree1_Leaves1.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_20.geometry} material={materials['Tree1_Leaves2.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_21.geometry} material={materials['Tree1_Trunk.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_22.geometry} material={materials['Tree2_Leaves1.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_23.geometry} material={materials['Tree2_Leaves2.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_24.geometry} material={materials['Tree2_Leaves3.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_25.geometry} material={materials['Tree2_Trunk.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_26.geometry} material={materials['Tree5_Leaves2.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_27.geometry} material={materials['Tree5_Leaves1.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_28.geometry} material={materials['Tree5_Trunk.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_29.geometry} material={materials['Tree3_Leaves1.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_30.geometry} material={materials['Tree3_Trunk.001']} />
      <mesh receiveShadow geometry={nodes.Cone001_31.geometry} material={materials['Tree1_Leaves1.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_32.geometry} material={materials['Tree1_Leaves2.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_33.geometry} material={materials['Tree1_Trunk.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_34.geometry} material={materials['Tree2_Leaves1.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_35.geometry} material={materials['Tree2_Leaves2.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_36.geometry} material={materials['Tree2_Leaves3.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_37.geometry} material={materials['Tree2_Trunk.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_38.geometry} material={materials['Tree3_Leaves1.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_39.geometry} material={materials['Tree3_Trunk.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_40.geometry} material={materials['Scene_-_Root']} />
      <mesh receiveShadow geometry={nodes.Cone001_41.geometry} material={materials['Material.004']} />
      <mesh receiveShadow geometry={nodes.Cone001_42.geometry} material={materials['Material.003']} />
      <mesh receiveShadow geometry={nodes.Cone001_43.geometry} material={materials['Material.002']} />
      <mesh receiveShadow geometry={nodes.Cone001_44.geometry} material={materials['Material.007']} />
      <mesh receiveShadow geometry={nodes.Cone001_45.geometry} material={materials['Material.005']} />
      <mesh receiveShadow geometry={nodes.Cone001_46.geometry} material={materials['Material.009']} />
      <mesh receiveShadow geometry={nodes.Cone001_47.geometry} material={materials['Material.010']} />
      <mesh receiveShadow geometry={nodes.Cone001_48.geometry} material={materials['Material.012']} />
      <mesh receiveShadow geometry={nodes.Cone001_49.geometry} material={materials['Material.013']} />
      <mesh receiveShadow geometry={nodes.Cone001_50.geometry} material={materials['Material.015']} />
    </group>
  )
}

useGLTF.preload(getModelPath('map1'))
