/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\map3\model.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cone007: THREE.Mesh
    Cone007_1: THREE.Mesh
    Cone007_2: THREE.Mesh
    Cone002: THREE.Mesh
    Cone002_1: THREE.Mesh
    Icosphere030: THREE.Mesh
    Icosphere030_1: THREE.Mesh
    Icosphere030_2: THREE.Mesh
    Icosphere030_3: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere003_1: THREE.Mesh
    Icosphere003_2: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001_2: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere001_1: THREE.Mesh
    Icosphere001_2: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere002_1: THREE.Mesh
    Icosphere002_2: THREE.Mesh
    Icosphere002_3: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cone003: THREE.Mesh
    Cone003_1: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere004_1: THREE.Mesh
    Icosphere004_2: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere005_1: THREE.Mesh
    Icosphere005_2: THREE.Mesh
    Icosphere005_3: THREE.Mesh
    Cone004: THREE.Mesh
    Cone004_1: THREE.Mesh
    montaña: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Tree5_Leaves2: THREE.MeshStandardMaterial
    Tree5_Leaves1: THREE.MeshStandardMaterial
    Tree5_Trunk: THREE.MeshStandardMaterial
    Tree4_Leaves1: THREE.MeshStandardMaterial
    Tree4_Leaves2: THREE.MeshStandardMaterial
    Tree4_Trunk: THREE.MeshStandardMaterial
    Tree3_Leaves1: THREE.MeshStandardMaterial
    Tree3_Trunk: THREE.MeshStandardMaterial
    Tree2_Leaves1: THREE.MeshStandardMaterial
    Tree2_Leaves2: THREE.MeshStandardMaterial
    Tree2_Leaves3: THREE.MeshStandardMaterial
    Tree2_Trunk: THREE.MeshStandardMaterial
    Tree1_Leaves1: THREE.MeshStandardMaterial
    Tree1_Leaves2: THREE.MeshStandardMaterial
    Tree1_Trunk: THREE.MeshStandardMaterial
    ['Tree4_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree4_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree4_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.001']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree5_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.002']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.002']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Map3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('map3')) as GLTFResult
  return (
    <>
      <group {...props} dispose={null}>
        <mesh receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.001']} />
        <group position={[-6.553, -30.506, -6.12]}>
          <mesh receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Tree5_Leaves2} />
          <mesh receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials.Tree5_Leaves1} />
          <mesh receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials.Tree5_Trunk} />
        </group>
        <group position={[-8.205, -22.991, -7.609]}>
          <mesh receiveShadow geometry={nodes.Cone007.geometry} material={materials.Tree4_Leaves1} />
          <mesh receiveShadow geometry={nodes.Cone007_1.geometry} material={materials.Tree4_Leaves2} />
          <mesh receiveShadow geometry={nodes.Cone007_2.geometry} material={materials.Tree4_Trunk} />
        </group>
        <group position={[-0.202, -2.61, -0.514]}>
          <mesh receiveShadow geometry={nodes.Cone002.geometry} material={materials.Tree3_Leaves1} />
          <mesh receiveShadow geometry={nodes.Cone002_1.geometry} material={materials.Tree3_Trunk} />
        </group>
        <group position={[58.542, -28.925, -32.548]}>
          <mesh receiveShadow geometry={nodes.Icosphere030.geometry} material={materials.Tree2_Leaves1} />
          <mesh receiveShadow geometry={nodes.Icosphere030_1.geometry} material={materials.Tree2_Leaves2} />
          <mesh receiveShadow geometry={nodes.Icosphere030_2.geometry} material={materials.Tree2_Leaves3} />
          <mesh receiveShadow geometry={nodes.Icosphere030_3.geometry} material={materials.Tree2_Trunk} />
        </group>
        <group position={[1.405, -14.282, 2.96]}>
          <mesh receiveShadow geometry={nodes.Icosphere003.geometry} material={materials.Tree1_Leaves1} />
          <mesh receiveShadow geometry={nodes.Icosphere003_1.geometry} material={materials.Tree1_Leaves2} />
          <mesh receiveShadow geometry={nodes.Icosphere003_2.geometry} material={materials.Tree1_Trunk} />
        </group>
        <group position={[6.326, -23.282, 2.888]}>
          <mesh receiveShadow geometry={nodes.Cone001.geometry} material={materials['Tree4_Leaves1.001']} />
          <mesh receiveShadow geometry={nodes.Cone001_1.geometry} material={materials['Tree4_Leaves2.001']} />
          <mesh receiveShadow geometry={nodes.Cone001_2.geometry} material={materials['Tree4_Trunk.001']} />
        </group>
        <group position={[0.413, -14.664, -0.479]}>
          <mesh receiveShadow geometry={nodes.Icosphere001.geometry} material={materials['Tree1_Leaves1.001']} />
          <mesh receiveShadow geometry={nodes.Icosphere001_1.geometry} material={materials['Tree1_Leaves2.001']} />
          <mesh receiveShadow geometry={nodes.Icosphere001_2.geometry} material={materials['Tree1_Trunk.001']} />
        </group>
        <group position={[6.96, -25.75, 1.891]}>
          <mesh receiveShadow geometry={nodes.Icosphere002.geometry} material={materials['Tree2_Leaves1.001']} />
          <mesh receiveShadow geometry={nodes.Icosphere002_1.geometry} material={materials['Tree2_Leaves2.001']} />
          <mesh receiveShadow geometry={nodes.Icosphere002_2.geometry} material={materials['Tree2_Leaves3.001']} />
          <mesh receiveShadow geometry={nodes.Icosphere002_3.geometry} material={materials['Tree2_Trunk.001']} />
        </group>
        <group position={[5.628, -32.958, 6.42]}>
          <mesh receiveShadow geometry={nodes.Cylinder001.geometry} material={materials['Tree5_Leaves2.001']} />
          <mesh receiveShadow geometry={nodes.Cylinder001_1.geometry} material={materials['Tree5_Leaves1.001']} />
          <mesh receiveShadow geometry={nodes.Cylinder001_2.geometry} material={materials['Tree5_Trunk.001']} />
        </group>
        <group position={[-0.022, -7, -0.977]}>
          <mesh receiveShadow geometry={nodes.Cone003.geometry} material={materials['Tree3_Leaves1.001']} />
          <mesh receiveShadow geometry={nodes.Cone003_1.geometry} material={materials['Tree3_Trunk.001']} />
        </group>
        <group position={[7.818, -34.443, -8.949]}>
          <mesh receiveShadow geometry={nodes.Icosphere004.geometry} material={materials['Tree1_Leaves1.002']} />
          <mesh receiveShadow geometry={nodes.Icosphere004_1.geometry} material={materials['Tree1_Leaves2.002']} />
          <mesh receiveShadow geometry={nodes.Icosphere004_2.geometry} material={materials['Tree1_Trunk.002']} />
        </group>
        <group position={[4.583, -32.581, -13.427]}>
          <mesh receiveShadow geometry={nodes.Icosphere005.geometry} material={materials['Tree2_Leaves1.002']} />
          <mesh receiveShadow geometry={nodes.Icosphere005_1.geometry} material={materials['Tree2_Leaves2.002']} />
          <mesh receiveShadow geometry={nodes.Icosphere005_2.geometry} material={materials['Tree2_Leaves3.002']} />
          <mesh receiveShadow geometry={nodes.Icosphere005_3.geometry} material={materials['Tree2_Trunk.002']} />
        </group>
        <group position={[-6.753, -32.273, -6.802]}>
          <mesh receiveShadow geometry={nodes.Cone004.geometry} material={materials['Tree3_Leaves1.002']} />
          <mesh receiveShadow geometry={nodes.Cone004_1.geometry} material={materials['Tree3_Trunk.002']} />
        </group>
        <mesh receiveShadow geometry={nodes.montaña.geometry} material={materials['Material.002']} position={[36.121, -6.579, 85.795]} rotation={[0.764, -1.564, 0.77]} scale={[14.868, 28.348, 31.441]} />
      </group>
    </>
  )
}

useGLTF.preload(getModelPath('map3'))
