/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\map3\model.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelPath } from '@/helpers/path'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cone007: THREE.Mesh
    Cone007_1: THREE.Mesh
    Cone007_2: THREE.Mesh
    Cone002: THREE.Mesh
    Cone002_1: THREE.Mesh
    Icosphere030: THREE.Mesh
    Icosphere030_1: THREE.Mesh
    Icosphere030_2: THREE.Mesh
    Icosphere030_3: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere003_1: THREE.Mesh
    Icosphere003_2: THREE.Mesh
    Cone001: THREE.Mesh
    Cone001_1: THREE.Mesh
    Cone001_2: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere001_1: THREE.Mesh
    Icosphere001_2: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere002_1: THREE.Mesh
    Icosphere002_2: THREE.Mesh
    Icosphere002_3: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cone003: THREE.Mesh
    Cone003_1: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere004_1: THREE.Mesh
    Icosphere004_2: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere005_1: THREE.Mesh
    Icosphere005_2: THREE.Mesh
    Icosphere005_3: THREE.Mesh
    Cone004: THREE.Mesh
    Cone004_1: THREE.Mesh
    montaña: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Tree5_Leaves2: THREE.MeshStandardMaterial
    Tree5_Leaves1: THREE.MeshStandardMaterial
    Tree5_Trunk: THREE.MeshStandardMaterial
    Tree4_Leaves1: THREE.MeshStandardMaterial
    Tree4_Leaves2: THREE.MeshStandardMaterial
    Tree4_Trunk: THREE.MeshStandardMaterial
    Tree3_Leaves1: THREE.MeshStandardMaterial
    Tree3_Trunk: THREE.MeshStandardMaterial
    Tree2_Leaves1: THREE.MeshStandardMaterial
    Tree2_Leaves2: THREE.MeshStandardMaterial
    Tree2_Leaves3: THREE.MeshStandardMaterial
    Tree2_Trunk: THREE.MeshStandardMaterial
    Tree1_Leaves1: THREE.MeshStandardMaterial
    Tree1_Leaves2: THREE.MeshStandardMaterial
    Tree1_Trunk: THREE.MeshStandardMaterial
    ['Tree4_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree4_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree4_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.001']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves2.001']: THREE.MeshStandardMaterial
    ['Tree5_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree5_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.001']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.001']: THREE.MeshStandardMaterial
    ['Tree1_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree1_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree1_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves2.002']: THREE.MeshStandardMaterial
    ['Tree2_Leaves3.002']: THREE.MeshStandardMaterial
    ['Tree2_Trunk.002']: THREE.MeshStandardMaterial
    ['Tree3_Leaves1.002']: THREE.MeshStandardMaterial
    ['Tree3_Trunk.002']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Map3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(getModelPath('map3')) as GLTFResult
  return (
    <>
      <group {...props} dispose={null}>
      <group>
        <group position={[-21.32, 4.405, -1.911]}>
          <mesh geometry={nodes.Cylinder.geometry} material={materials.Tree5_Leaves2} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Tree5_Leaves1} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Tree5_Trunk} />
        </group>
        <group position={[32.017, -6.354, 6.742]}>
          <mesh geometry={nodes.Cone007.geometry} material={materials.Tree4_Leaves1} />
          <mesh geometry={nodes.Cone007_1.geometry} material={materials.Tree4_Leaves2} />
          <mesh geometry={nodes.Cone007_2.geometry} material={materials.Tree4_Trunk} />
        </group>
        <group position={[140.492, 2.11, 41.317]}>
          <mesh geometry={nodes.Cone002.geometry} material={materials.Tree3_Leaves1} />
          <mesh geometry={nodes.Cone002_1.geometry} material={materials.Tree3_Trunk} />
        </group>
        <group position={[1.401, 6.558, 19.618]}>
          <mesh geometry={nodes.Icosphere030.geometry} material={materials.Tree2_Leaves1} />
          <mesh geometry={nodes.Icosphere030_1.geometry} material={materials.Tree2_Leaves2} />
          <mesh geometry={nodes.Icosphere030_2.geometry} material={materials.Tree2_Leaves3} />
          <mesh geometry={nodes.Icosphere030_3.geometry} material={materials.Tree2_Trunk} />
        </group>
        <group position={[16.102, 8.456, -34.233]}>
          <mesh geometry={nodes.Icosphere003.geometry} material={materials.Tree1_Leaves1} />
          <mesh geometry={nodes.Icosphere003_1.geometry} material={materials.Tree1_Leaves2} />
          <mesh geometry={nodes.Icosphere003_2.geometry} material={materials.Tree1_Trunk} />
        </group>
        <group position={[-29.331, -9.414, 38.299]}>
          <mesh geometry={nodes.Cone001.geometry} material={materials['Tree4_Leaves1.001']} />
          <mesh geometry={nodes.Cone001_1.geometry} material={materials['Tree4_Leaves2.001']} />
          <mesh geometry={nodes.Cone001_2.geometry} material={materials['Tree4_Trunk.001']} />
        </group>
        <group position={[1.106, 6.823, -8.689]}>
          <mesh geometry={nodes.Icosphere001.geometry} material={materials['Tree1_Leaves1.001']} />
          <mesh
            geometry={nodes.Icosphere001_1.geometry}
            material={materials['Tree1_Leaves2.001']}
          />
          <mesh geometry={nodes.Icosphere001_2.geometry} material={materials['Tree1_Trunk.001']} />
        </group>
        <group position={[15.758, 9.568, 2.244]}>
          <mesh geometry={nodes.Icosphere002.geometry} material={materials['Tree2_Leaves1.001']} />
          <mesh
            geometry={nodes.Icosphere002_1.geometry}
            material={materials['Tree2_Leaves2.001']}
          />
          <mesh
            geometry={nodes.Icosphere002_2.geometry}
            material={materials['Tree2_Leaves3.001']}
          />
          <mesh geometry={nodes.Icosphere002_3.geometry} material={materials['Tree2_Trunk.001']} />
        </group>
        <group position={[-186.677, 5.053, 53]} scale={1.126}>
          <mesh geometry={nodes.Cylinder001.geometry} material={materials['Tree5_Leaves2.001']} />
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Tree5_Leaves1.001']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Tree5_Trunk.001']} />
        </group>
        <group position={[52.517, 0.469, -33.365]}>
          <mesh geometry={nodes.Cone003.geometry} material={materials['Tree3_Leaves1.001']} />
          <mesh geometry={nodes.Cone003_1.geometry} material={materials['Tree3_Trunk.001']} />
        </group>
        <group position={[11.646, 6.222, -9.027]}>
          <mesh geometry={nodes.Icosphere004.geometry} material={materials['Tree1_Leaves1.002']} />
          <mesh
            geometry={nodes.Icosphere004_1.geometry}
            material={materials['Tree1_Leaves2.002']}
          />
          <mesh geometry={nodes.Icosphere004_2.geometry} material={materials['Tree1_Trunk.002']} />
        </group>
        <group position={[0.346, 5.096, 7.261]}>
          <mesh geometry={nodes.Icosphere005.geometry} material={materials['Tree2_Leaves1.002']} />
          <mesh
            geometry={nodes.Icosphere005_1.geometry}
            material={materials['Tree2_Leaves2.002']}
          />
          <mesh
            geometry={nodes.Icosphere005_2.geometry}
            material={materials['Tree2_Leaves3.002']}
          />
          <mesh geometry={nodes.Icosphere005_3.geometry} material={materials['Tree2_Trunk.002']} />
        </group>
        <group position={[-16.535, -0.779, 48.281]}>
          <mesh geometry={nodes.Cone004.geometry} material={materials['Tree3_Leaves1.002']} />
          <mesh geometry={nodes.Cone004_1.geometry} material={materials['Tree3_Trunk.002']} />
        </group>
        <group position={[44.204, 6.688, 18.88]}>
          <mesh geometry={nodes.Icosphere006.geometry} material={materials['Tree2_Leaves1.003']} />
          <mesh
            geometry={nodes.Icosphere006_1.geometry}
            material={materials['Tree2_Leaves2.003']}
          />
          <mesh
            geometry={nodes.Icosphere006_2.geometry}
            material={materials['Tree2_Leaves3.003']}
          />
          <mesh geometry={nodes.Icosphere006_3.geometry} material={materials['Tree2_Trunk.003']} />
        </group>
        <group position={[-4.445, 15.832, 117.421]}>
          <mesh geometry={nodes.Icosphere007.geometry} material={materials['Tree2_Leaves1.004']} />
          <mesh
            geometry={nodes.Icosphere007_1.geometry}
            material={materials['Tree2_Leaves2.004']}
          />
          <mesh
            geometry={nodes.Icosphere007_2.geometry}
            material={materials['Tree2_Leaves3.004']}
          />
          <mesh geometry={nodes.Icosphere007_3.geometry} material={materials['Tree2_Trunk.004']} />
        </group>
        <group position={[76.774, 2.655, 45.376]}>
          <mesh geometry={nodes.Icosphere008.geometry} material={materials['Tree2_Leaves1.005']} />
          <mesh
            geometry={nodes.Icosphere008_1.geometry}
            material={materials['Tree2_Leaves2.005']}
          />
          <mesh
            geometry={nodes.Icosphere008_2.geometry}
            material={materials['Tree2_Leaves3.005']}
          />
          <mesh geometry={nodes.Icosphere008_3.geometry} material={materials['Tree2_Trunk.005']} />
        </group>
        <group position={[27.111, -1.635, 38.8]}>
          <mesh geometry={nodes.Cone005.geometry} material={materials['Tree4_Leaves1.002']} />
          <mesh geometry={nodes.Cone005_1.geometry} material={materials['Tree4_Leaves2.002']} />
          <mesh geometry={nodes.Cone005_2.geometry} material={materials['Tree4_Trunk.002']} />
        </group>
        <group position={[95.535, 9.208, 58.148]}>
          <mesh geometry={nodes.Icosphere009.geometry} material={materials['Tree2_Leaves1.006']} />
          <mesh
            geometry={nodes.Icosphere009_1.geometry}
            material={materials['Tree2_Leaves2.006']}
          />
          <mesh
            geometry={nodes.Icosphere009_2.geometry}
            material={materials['Tree2_Leaves3.006']}
          />
          <mesh geometry={nodes.Icosphere009_3.geometry} material={materials['Tree2_Trunk.006']} />
        </group>
        <group position={[106.084, 13.721, 83.953]}>
          <mesh geometry={nodes.Cylinder003.geometry} material={materials['Tree5_Leaves2.002']} />
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Tree5_Leaves1.002']} />
          <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Tree5_Trunk.002']} />
        </group>
        <group position={[39.252, 21.484, 107.444]}>
          <mesh geometry={nodes.Cylinder004.geometry} material={materials['Tree5_Leaves2.003']} />
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Tree5_Leaves1.003']} />
          <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Tree5_Trunk.003']} />
        </group>
        <group position={[21.662, -2.152, -40.263]}>
          <mesh geometry={nodes.Cone006.geometry} material={materials['Tree3_Leaves1.003']} />
          <mesh geometry={nodes.Cone006_1.geometry} material={materials['Tree3_Trunk.003']} />
        </group>
        <group position={[100.413, 5.522, -85.884]}>
          <mesh geometry={nodes.Cone008.geometry} material={materials['Tree3_Leaves1.004']} />
          <mesh geometry={nodes.Cone008_1.geometry} material={materials['Tree3_Trunk.004']} />
        </group>
        <group position={[50.944, 14.204, 129.161]}>
          <mesh geometry={nodes.Cylinder005.geometry} material={materials['Tree5_Leaves2.004']} />
          <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Tree5_Leaves1.004']} />
          <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Tree5_Trunk.004']} />
        </group>
        <group position={[77.793, 19.406, 104.373]}>
          <mesh geometry={nodes.Icosphere010.geometry} material={materials['Tree2_Leaves1.007']} />
          <mesh
            geometry={nodes.Icosphere010_1.geometry}
            material={materials['Tree2_Leaves2.007']}
          />
          <mesh
            geometry={nodes.Icosphere010_2.geometry}
            material={materials['Tree2_Leaves3.007']}
          />
          <mesh geometry={nodes.Icosphere010_3.geometry} material={materials['Tree2_Trunk.007']} />
        </group>
        <group position={[-69.616, 16.002, 107.227]} scale={1.126}>
          <mesh geometry={nodes.Cylinder006.geometry} material={materials['Tree5_Leaves2.005']} />
          <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Tree5_Leaves1.005']} />
          <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Tree5_Trunk.005']} />
        </group>
        <group position={[94.816, -3.264, -142.364]}>
          <mesh geometry={nodes.Cone009.geometry} material={materials['Tree4_Leaves1.003']} />
          <mesh geometry={nodes.Cone009_1.geometry} material={materials['Tree4_Leaves2.003']} />
          <mesh geometry={nodes.Cone009_2.geometry} material={materials['Tree4_Trunk.003']} />
        </group>
        <group position={[149.198, 5.804, 49.278]}>
          <mesh geometry={nodes.Icosphere011.geometry} material={materials['Tree1_Leaves1.003']} />
          <mesh
            geometry={nodes.Icosphere011_1.geometry}
            material={materials['Tree1_Leaves2.003']}
          />
          <mesh geometry={nodes.Icosphere011_2.geometry} material={materials['Tree1_Trunk.003']} />
        </group>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} />
      </group>
    </group>
    </>
  )
}

useGLTF.preload(getModelPath('map3'))
