/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/priest/model.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { getModelPath } from '../helpers/path'

export function Priest({withAnimations = false, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(getModelPath('priest'))
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (withAnimations) {
      actions['Idle'].reset().fadeIn(0.5).play();
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="KayKit_Animated_Character">
          <primitive object={nodes.Body} />
          <skinnedMesh name="outline" geometry={nodes.outline.geometry} material={materials.outline} skeleton={nodes.outline.skeleton} />
          <skinnedMesh name="PrototypePete" geometry={nodes.PrototypePete.geometry} material={materials.PrototypePete} skeleton={nodes.PrototypePete.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getModelPath('priest'))